# Generated by Django 4.1.3 on 2023-03-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgethub', '0003_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='createdAt',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
