# Generated by Django 4.1.3 on 2023-03-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgethub', '0005_order_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderNumber',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
