# Generated by Django 4.1.3 on 2023-03-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgethub', '0012_alter_itemimages_image_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimages',
            name='image',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
