# Generated by Django 4.1.3 on 2023-03-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgethub', '0014_remove_itemimages_image_itemimages_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemimages',
            name='title',
        ),
        migrations.AddField(
            model_name='itemimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
