# Generated by Django 4.1.3 on 2023-03-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgethub', '0015_remove_itemimages_title_itemimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimages',
            name='image',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
