# Generated by Django 4.1.3 on 2023-03-22 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gadgethub', '0016_alter_itemimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimages',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to='gadgethub.product'),
        ),
    ]
