# Generated by Django 4.1.3 on 2023-03-24 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gadgethub', '0025_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_img',
        ),
    ]
