# Generated by Django 4.1.3 on 2023-03-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgethub', '0027_orderitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
    ]
