# Generated by Django 4.1.3 on 2023-03-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgethub', '0031_product_issold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isSaved',
            field=models.BooleanField(default=False),
        ),
    ]
